Vishal Gadekar (PCET's NCER) Assignment week 4

#Applying Bayes' Theorem to a Medical Diagnosis Problem
**Problem Statement**: Suppose a certain disease affects 1% of the population. There is a test for the disease which is 99% sensitive (true positive rate) and 95% specific (true negative rate). We need to find the probability that a person actually has the disease given that they tested positive.

Given:

P(D)=0.01 (*Prevalence of the disease*)

P(T
+
 ∣D)=0.99 (*Sensitivity*)



P(T
−
 ∣D
−
 )=0.95 (*Specificity*)

 P(T
+
 ∣D
−
 ) (*Probability of a false positive*)

P(T
+
 ∣D
−
 )
 = 1−P(T
−
 ∣D
−
 )

 =1−0.95=0.05

In [8]:
import numpy as np
import scipy.stats as stats

1. Bayes' Theorem for Medical *Diagnosis*

Using Bayes' Theorem:    
 P(D∣T
+
 )=
P(T
+
 )
P(T
+
 ∣D)P(D)

To find \( P(T +) \):

\[ P(T +) = P(T + | D)P(D) + P(T + | D -)P(D -) \]

\[ P(T +) = (0.99 \times 0.01) + (0.05 \times 0.99) \]

\[ P(T +) = 0.0099 + 0.0495 = ***0.0594*** \]

In [9]:
P_D = 0.01
P_T_given_D = 0.99
P_T_given_not_D = 0.05
P_not_D = 1 - P_D
P_T = (P_T_given_D * P_D) + (P_T_given_not_D * P_not_D)
P_D_given_T = (P_T_given_D * P_D) / P_T

2. Eigenvalues and Eigenvectors

Matrix:
\[ A = \begin{pmatrix} 4 & 1 \\ 2 & 3 \end{pmatrix} \]

To find the eigenvalues \(λ\), we solve the characteristic equation:
\[ (A - λ I) = 0 \]

\[ \begin{vmatrix} 4 - λ & 1 \\ 2 & 3 - λ \end{vmatrix} = 0 \]

\[ (4 - λ)(3 - λ) - 2 · 1 = 0 \]

\[ λ^2 - 7λ + 10 = 0 \]

\[ (λ - 5)(λ - 2) = 0 \]


So, the eigenvalues are \(λ_1 = 5\) and \(λ_2 = 2\).


Now find the eigenvectors for each eigenvalue.

For \(λ_1 = 5\):
\[ (A - 5I)v = 0 \]

\[ \begin{pmatrix} -1 & 1 \\ 2 & -2 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \end{pmatrix} \]

\[ -x + y = 0 \]

\[ y = x \]


Eigenvector corresponding to \(λ_1 = 5\) is \( v_1 = k \begin{pmatrix} 1 \\ 1 \end{pmatrix} \).

For \(λ_2 = 2\):
\[ (A - 2I)v = 0 \]
\[ \begin{pmatrix} 2 & 1 \\ 2 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \end{pmatrix} \]

\[ 2x + y = 0 \]

\[ y = -2x \]

Eigenvector corresponding to \(λ_2 = 2\) is \( v_2 = k \begin{pmatrix} 1 \\ -2 \end{pmatrix} \).

In [10]:
A = np.array([[4, 1], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

3. Determinant and Inverse of a 3x3 Matrix

Matrix:
\[ B = \begin{pmatrix} 1 & 2 & 3 \\ 0 & 1 & 4 \\ 5 & 6 & 0 \end{pmatrix} \]

The determinant \(**det**(B)\) is:

\[ **det**(B) = 1 · (1 · 0 - 4 · 6) - 2 · (0 · 0 - 4 · 5) + 3 · (0 · 6 - 1 · 5) \]

\[ **det**(B) = 1 · (0 - 24) - 2 · (0 - 20) + 3 · (0 - 5) \]

\[ **det**(B) = -24 + 40 - 15 \]

\[ **det**(B) = 1 \]


Since \(**det**(B) =! 0\), \( B \) is invertible. We can find the inverse using the formula:
\[ B^{-1} = (1/**det**(B)) **adj**(B) \]


The adjugate matrix \(**adj**(B)\) is the transpose of the cofactor matrix. We calculate the cofactors and then transpose.


Cofactors of \( B \):
\[ C_{11} = **det** \begin{pmatrix} 1 & 4 \\ 6 & 0 \end{pmatrix} = -24 \]
\[ C_{12} = -**det** \begin{pmatrix} 0 & 4 \\ 5 & 0 \end{pmatrix} = -20 \]
\[ C_{13} = **det** \begin{pmatrix} 0 & 1 \\ 5 & 6 \end{pmatrix} = -5 \]
\[ C_{21} = -**det** \begin{pmatrix} 2 & 3 \\ 6 & 0 \end{pmatrix} = 18 \]
\[ C_{22} = **det** \begin{pmatrix} 1 & 3 \\ 5 & 0 \end{pmatrix} = -15 \]
\[ C_{23} = -**det** \begin{pmatrix} 1 & 2 \\ 5 & 6 \end{pmatrix} = 4 \]
\[ C_{31} = **det** \begin{pmatrix} 2 & 3 \\ 1 & 4 \end{pmatrix} = 5 \]
\[ C_{32} = -**det** \begin{pmatrix} 1 & 3 \\ 0 & 4 \end{pmatrix} = -4 \]
\[ C_{33} = **det** \begin{pmatrix} 1 & 2 \\ 0 & 1 \end{pmatrix} = 1 \]

So, the cofactor matrix is:
\[ **Cof**(B) = \begin{pmatrix} -24 & -20 & -5 \\ 18 & -15 & 4 \\ 5 & -4 & 1 \end{pmatrix} \]

Transposing gives the adjugate matrix:
\[ **adj**(B) = \begin{pmatrix} -24 & 18 & 5 \\ -20 & -15 & -4 \\ -5 & 4 & 1 \end{pmatrix} \]

Finally, the inverse is:
\[ B^{-1} = 1/1(

  
 \begin{pmatrix} -24 & 18 & 5 \\ -20 & -15 & -4 \\ -5 & 4 & 1 \end{pmatrix} )

 = \begin{pmatrix} -24 & 18 & 5 \\ -20 & -15 & -4 \\ -5 & 4 & 1 \end{pmatrix} ]

In [11]:
B = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det_B = np.linalg.det(B)
inverse_B = np.linalg.inv(B) if det_B != 0 else None

4. Normal Distribution Probability

In [18]:
mu = 100
sigma = 15
X = 120
z = (X - mu) / sigma
probability = stats.norm.cdf(z)

P_D_given_T, eigenvalues, eigenvectors, det_B, inverse_B, probability

(0.16666666666666669,
 array([5., 2.]),
 array([[ 0.70710678, -0.4472136 ],
        [ 0.70710678,  0.89442719]]),
 0.9999999999999964,
 array([[-24.,  18.,   5.],
        [ 20., -15.,  -4.],
        [ -5.,   4.,   1.]]),
 0.9087887802741321)

So, the probability that X is less than 120 is approximately ***90.82%***.